## Multilayer Preceptron

In [30]:
import matplotlib.pyplot as plt

In [31]:
import numpy as np

In [32]:
x1, x2 = 3,7
x = np.array([x1,x2])

In [33]:
x

array([3, 7])

In [34]:
w = np.array([ [1,3,5],[2,4,6]])

In [35]:
x.shape
w.shape

(2, 3)

In [36]:
np.dot(x,w)


array([17, 37, 57])

##Lets get z(1)

In [37]:
x = np.array([0.7,0.8])
w1 = np.array([[0.5,0.6,0.7],[0.1,0.2,0.3]])
b1 = np.array([0.2,0.3,0.9])

a1 = np.dot(x,w1) + b1

# Define sigmoid

In [38]:
def sigmoid(s):
    return 1/(1 + np.exp(-s))

In [39]:
z1 = sigmoid(a1)

In [40]:
z1

array([0.65248946, 0.70682222, 0.83616964])

In [41]:
w2 = np.array([[0.5,0.6],[0.1,0.2],[0.3,0.7]])
b2 = np.array([0.2,0.9])

a2 = np.dot(z1,w2) + b2

In [42]:
z2 = sigmoid(a2)

In [43]:
def identity_function(z):
    return z

In [44]:
y  = identity_function(z2)

In [45]:
y

array([0.70010079, 0.88269236])

In [46]:
def init_network():
    network = {}
    network['w1'] = np.array([[0.5,0.6,0.7],[0.1,0.2,0.3]])
    network ['b1'] = np.array([0.2,0.3,0.9])
    network['w2'] = np.array([[0.5,0.6],[0.1,0.2],[0.3,0.7]])
    network ['b2'] = np.array([0.2,0.9])
    network['w3'] = np.array([[0.5,0.4],[0.1254,0.2463]])
    network ['b3'] = np.array([0.2546164,0.9565465])

    return network


In [47]:
def forward(network, x):
    w1,w2,w3 = network['w1'], network['w2'], network['w3']
    b1,b2,b3 = network['b1'], network['b2'], network['b3']

    a1 = np.dot(x,w1) + b1
    z1 = sigmoid(a1)

    a2 = np.dot(z1,w2) + b2
    z2 = sigmoid(a2)

    a3 = np.dot(z2,w3) + b3
    y = identity_function(a3)

    return y


In [48]:
network = init_network()
x = np.array([0.13554, 0.448765])
y = forward(network, x)

In [68]:
class MultilyerPerceptron():
    def __init__(self):
        self.network = {}
        self.network['w1'] = np.array([[0.5,0.6,0.7],[0.1,0.2,0.3]])
        self.network ['b1'] = np.array([0.2,0.3,0.9])
        self.network['w2'] = np.array([[0.5,0.6],[0.1,0.2],[0.3,0.7]])
        self.network ['b2'] = np.array([0.2,0.9])
        self.network['w3'] = np.array([[0.5,0.4],[0.1254,0.2463]])
        self.network ['b3'] = np.array([0.2546164,0.9565465])

    def sigmoid(self,s):
        return 1/(1 + np.exp(-s))

    def identity_function(self, s):
        return s
    

    def forward(self, x):
        w1,w2,w3 = self.network['w1'], self.network['w2'], self.network['w3']
        b1,b2,b3 = self.network['b1'], self.network['b2'], self.network['b3']

        a1 = np.dot(x,w1) + b1
        z1 = self.sigmoid(a1)

        a2 = np.dot(z1,w2) + b2
        z2 = self.sigmoid(a2)

        a3 = np.dot(z2,w3) + b3
        y = self.identity_function(a3)

        return y

In [70]:
mlp = MultilyerPerceptron()
y = mlp.forward(np.array([[0.25423, 0.1694464]]))
print(y)

[[0.70672522 1.4452845 ]]
